### ISSUE TITLE
SD Card not detected on STM32F405

### ISSUE THREAD

**Issue by jerryneedell** [adafruit/Adafruit_CircuitPython_SD#36]
I am unable to access an SDCard - using an Adalloger Featherwing on a feather_stm32f405_featherwing.

```
Press any key to enter the REPL. Use CTRL-D to reload.
Adafruit CircuitPython 6.0.0-alpha.1-111-g8f928340c on 2020-07-20; Feather STM32F405 Express with STM32F405RG
>>> import sdmount_lib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sdmount_lib.py", line 9, in <module>
  File "adafruit_sdcard.py", line 116, in __init__
  File "adafruit_sdcard.py", line 177, in _init_card
  File "adafruit_sdcard.py", line 145, in _init_card
OSError: no SD card
>>> 
```
code executed  - sdmount_lib
```
import adafruit_sdcard
import busio
import digitalio
import board
import storage
import sys
# Connect to the card and mount the filesystem.
cs = digitalio.DigitalInOut(board.D10)
sdcard = adafruit_sdcard.SDCard(board.SPI(), cs)
vfs = storage.VfsFat(sdcard)
storage.mount(vfs, "/sd")
sys.path.append("/sd")
sys.path.append("/sd/lib")
```

**Comment by jepler** [comment]
We believe this should have been fixed by https://github.com/adafruit/circuitpython/issues/3176, please feel free to re-open if this is not the case.
